name: bot-discord

services:
    bot:
        image: cvjeticaxel122/crazybot:latest
        build:
            dockerfile: Dockerfile
        container_name: bot
        restart: on-failure:3
        env_file:
            - .env
        volumes:
            - ./config.js:/bot/config.js:ro
        networks:
            - bot-network
        depends_on:
            db:
                condition: service_healthy
            cache:
                condition: service_healthy

    db:
        image: postgres:14-alpine3.20
        container_name: db
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 30s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: crazybot
        ports:
            - "5432:5432"
        volumes:
            - ./DB.sql:/docker-entrypoint-initdb.d/DB.sql:ro
        networks:
            - bot-network

    cache:
        image: redis:7.4.1-alpine3.20
        container_name: cache
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
            interval: 30s
            timeout: 3s
            retries: 5
        command: ["redis-server", "--save", "", "--appendonly", "no"]
        ports:
            - "6379:6379"
        networks:
            - bot-network

networks:
    bot-network:
        name: bot-network
